"""Generate product image IDs in PostgreSQL.

Revision ID: c6b19e0d4f2a
Revises: b3f13a88f22a
"""

from alembic import op


# PRODUCT-02: Keep the existing composite key and let PostgreSQL assign image_id.
revision = "c6b19e0d4f2a"
down_revision = "b3f13a88f22a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Existing rows remain valid; the next generated ID starts after their maximum.
    op.execute(
        "ALTER TABLE product_images "
        "ALTER COLUMN image_id ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('product_images', 'image_id'), "
        "COALESCE((SELECT MAX(image_id) FROM product_images), 1), "
        "EXISTS (SELECT 1 FROM product_images))"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE product_images ALTER COLUMN image_id DROP IDENTITY")
